spring.application.name=backend
server.port=8081
management.endpoint.health.show-details=always

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.hgcqyeqtdqmlgzlhogbz
spring.datasource.password=Vc-&NcV6wbL%*Zk
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Configuration (ES256 Asymmetric Keys)
jwt.private.key=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCCcNEoU0y0Xd2wPshIU+4mrh2q/koZ4O/rIg0JFqcIZaA==
jwt.public.key=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEA5WpS8c3suT3iXQlro+Er2eDxlct6ah9kRYNxIjCqFp7SIZPlb2v9Bf+i8WQFVM5Cvt5toIl18ezPaF0amO1ig==

# Token Expiration Times
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# Application Security & CORS Settings (Environment Variables in Render)
app.cookie.secure=false
app.cookie.same-site=Lax
app.cors.allowed-origins=http://localhost:3000
